name: spruceTesting
description: Door knocking Flutter App to make it easier for going door to door and collecting data.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"
dependencies:
  bloc: ^8.1.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  go_router: ^13.2.0
  google_fonts: ^6.1.0
  http: ^1.1.0
  webfeed: ^0.7.0
  url_launcher: ^6.0.10
  cached_network_image: ^3.2.0
  responsive_framework: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
